import {createJob,validateJob,parseMoney,total,saveRevision,approveJob,makeExport,verifyExport} from './model.mjs';
import {validateWorkspace,readStored,writeStored,makeBackup,readBackup,workspaceSummary,MAX_BACKUP_BYTES} from './recovery.mjs';
const $=id=>document.getElementById(id), KEY='baystead.browser.v3', clone=v=>structuredClone(v), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const checks=[['BROWSER01','Load six fictional parts; original total $2,420.00.'],['BROWSER02','Invalid money is rejected; saved values stay unchanged.'],['BROWSER03','Save line 010 at $649 with a reason; total $2,434.00.'],['BROWSER04','Review, confirm, approve and export the saved revision.'],['BROWSER05','A later saved edit clears approval and blocks export.'],['BROWSER06','Reopen the approved browser export; check current or historical status.'],['BROWSER07','Create, edit and complete an internal task; refresh and check it.'],['BROWSER08','Refresh preserves saved work; drafts warn before leaving; no shared sync.']];
let state={job:null,tasks:[],qa:{}},dirty=false,pendingFile=null,storageBroken=false,editingTask=null,baseline=null,previous=null,pendingRestore=null,previewSerial=0; 
function notice(t,error=false){$('notice').textContent=t;$('notice').classList.toggle('error',error)}
function validState(s){return validateWorkspace(s)}
try{const raw=localStorage.getItem(KEY);baseline=raw;const stored=readStored(raw);state=stored.current;previous=stored.previous}catch{storageBroken=true;notice('Saved browser data could not be read. Nothing was overwritten. Ask Steen before resetting this browser workspace.',true)}
function assertFresh(){if(localStorage.getItem(KEY)!==baseline)throw Error('This workspace changed in another tab. Nothing was replaced. Reload to use the latest saved work.')}
function commit(next,rollback=null){
  validState(next);
  if(storageBroken)throw Error('Browser data could not be read. Resolve the storage issue or deliberately reset this fictional workspace.');
  try{baseline=writeStored(localStorage,KEY,baseline,next,rollback)}catch(e){if(e.message.includes('another tab'))throw e;throw Error('Browser storage is unavailable or full. This change was not saved. Keep this page open and contact Steen.')}
  state=next;previous=rollback;clearBackupLink();clearRestorePreview();recoveryControls();
}
function hasDraft(){return dirty||!!$('tasktext').value.trim()||!!$('taskowner').value.trim()}
function requireClean(){if(hasDraft())throw Error('Save or discard your part and task drafts before using backup or restore.');if(qaUnsaved)throw Error('Some test notes could not be saved. Download your typed test results before reloading.');if(storageBroken)throw Error('Saved data could not be read. Ask Steen before replacing this workspace.');assertFresh()}
let qaUnsaved=false,backupURL=null;
function controls(){const j=state.job;$('approve').disabled=!j||j.version<1||!!j.approved||dirty||!$('confirm').checked;$('export').disabled=!j?.approved||dirty;$('save-status').textContent=dirty?'Unsaved draft':j?j.approved?'Approved locally':'Saved locally':'No job loaded';$('save-status').classList.toggle('dirty',dirty);$('save').disabled=!j||!dirty;$('discard').disabled=!dirty}
function metrics(){const j=state.job;$('metric-lines').textContent=j?j.parts.length:'—';$('metric-total').textContent=j?money(total(j.parts)):'—';$('metric-original').textContent=j?'Original '+money(total(j.original.parts)):'Load a sample to begin';$('metric-review').textContent=j?j.approved?'Approved':'Needs review':'Not started';$('metric-revision').textContent=j?'Saved revision '+j.version:'No saved revision';const open=state.tasks.filter(t=>!t.done).length;$('metric-tasks').textContent=open;$('task-count').textContent=open+' open'}
function renderJob(){const j=state.job;$('empty').hidden=!!j;$('editor').hidden=!j;$('job-title').textContent=j?j.estimateId:'Ready when you are.';$('job-meta').textContent=j?j.locationId+' · '+j.vehicle:'PARTS REVIEW';dirty=false;$('confirm').checked=false;$('reason').value='';if(j){$('lines').innerHTML=j.parts.map((p,i)=>'<tr><td><small>LINE '+esc(p.lineId)+' · '+esc(p.partType)+'</small><strong>'+esc(p.description)+'</strong><small>'+esc(p.partNumber)+' · '+esc(p.supplier)+'</small></td><td>'+money(j.original.parts[i].unitPriceCents)+'<small>Qty '+j.original.parts[i].quantity+'</small></td><td><input aria-label="Line '+esc(p.lineId)+' quantity" data-quantity="'+i+'" inputmode="numeric" maxlength="3" value="'+p.quantity+'"></td><td><input aria-label="Line '+esc(p.lineId)+' unit price" data-price="'+i+'" inputmode="decimal" maxlength="12" value="'+(p.unitPriceCents/100).toFixed(2)+'"></td><td>'+money(p.quantity*p.unitPriceCents)+'</td></tr>').join('');const differences=j.parts.flatMap((p,i)=>['quantity','unitPriceCents'].filter(k=>p[k]!==j.original.parts[i][k]).map(k=>'<div class="diff-row"><b>Line '+esc(p.lineId)+' · '+(k==='quantity'?'Quantity':'Unit price')+'</b><span>'+display(k,j.original.parts[i][k])+' → '+display(k,p[k])+'</span></div>'));$('diff').innerHTML=differences.join('')||'<p class="subtle">No differences from the original snapshot.</p>'; $('history').innerHTML=j.history.map(h=>'<div class="history-item"><b>Revision '+h.version+'</b><small>'+esc(new Date(h.savedAt).toLocaleString())+'</small><p>'+esc(h.reason)+'</p><ul>'+h.changes.map(c=>'<li>Line '+esc(c.lineId)+' · '+(c.field==='quantity'?'Quantity':'Unit price')+': '+display(c.field,c.before)+' → '+display(c.field,c.after)+'</li>').join('')+'</ul></div>').reverse().join('')||'<p class="subtle">Original imported. Save a change to start the revision history.</p>'}else{$('history').innerHTML='<p class="subtle">Your saved revisions will appear here.</p>'}metrics();controls()}
function display(field,n){return field==='unitPriceCents'?money(n):String(n)}
function updateDirty(){if(!state.job)return;dirty=[...document.querySelectorAll('[data-price]')].some(x=>x.value!==(state.job.parts[+x.dataset.price].unitPriceCents/100).toFixed(2))||[...document.querySelectorAll('[data-quantity]')].some(x=>x.value!==String(state.job.parts[+x.dataset.quantity].quantity))||!!$('reason').value.trim();if(dirty)$('confirm').checked=false;controls()}
$('lines').addEventListener('input',updateDirty);$('reason').addEventListener('input',updateDirty);$('confirm').addEventListener('change',controls);
function load(){try{if(!state.job){const n=clone(state);n.job=createJob();commit(n);renderJob();notice('Six fictional parts loaded. Original total: $2,420.00.')}else{notice('Your saved sample is already open. Use its current values, or reset the fictional workspace for a fresh test.')} $('workbench').scrollIntoView({behavior:'smooth'})}catch(e){notice(e.message,true)}}
$('load').onclick=$('sample').onclick=load;
$('save').onclick=()=>{try{const parts=state.job.parts.map((p,i)=>{const raw=document.querySelector('[data-quantity="'+i+'"]').value.trim();if(!/^\d{1,3}$/.test(raw))throw Error('Line '+p.lineId+': quantity must be a whole number from 1 to 100.');return {...p,quantity:Number(raw),unitPriceCents:parseMoney(document.querySelector('[data-price="'+i+'"]').value)}});const next=clone(state);next.job=saveRevision(state.job,parts,$('reason').value);commit(next);renderJob();notice('Revision '+state.job.version+' saved. Review the exact changes before approving.')}catch(e){notice(e.message,true)}};
$('discard').onclick=()=>{if(dirty&&confirm('Discard unsaved part changes and the draft reason?')){renderJob();notice('Draft discarded. Your saved revision is unchanged.')}};
$('approve').onclick=()=>{try{if(dirty||!$('confirm').checked)throw Error('Save the draft and check the review confirmation first.');const n=clone(state);n.job=approveJob(state.job);commit(n);renderJob();notice('Revision '+state.job.version+' approved for this local review.')}catch(e){notice(e.message,true)}};
function download(filename,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=async()=>{try{if(dirty)throw Error('Save or discard the current draft first.');const packet=await makeExport(state.job);download('Baystead-Browser-Review-r'+state.job.version+'.json',JSON.stringify(packet,null,2),'application/json');notice('Browser review file prepared for download. Save it before running the verifier.')}catch(e){notice(e.message,true)}};
$('import').onchange=()=>{pendingFile=$('import').files[0]||null;$('verifyresult').textContent=''};
$('verify').onclick=async()=>{try{if(!pendingFile)throw Error('Choose a browser review JSON file first.');if(pendingFile.size>1048576)throw Error('Choose a browser review file smaller than 1 MB.');const result=await verifyExport(JSON.parse(await pendingFile.text()),state.job);$('verifyresult').classList.remove('error');$('verifyresult').textContent='PASS / '+result.status+'. File integrity verified. SHA-256 '+result.sha256}catch(e){$('verifyresult').classList.add('error');$('verifyresult').textContent='BLOCKED / '+e.message}};
function renderTasks(){metrics();$('tasks').innerHTML=state.tasks.length?state.tasks.map(t=>'<div class="task-row '+(t.done?'done':'')+'"><div><strong>'+esc(t.text)+'</strong><small>'+esc(t.owner||'Unassigned')+' · '+(t.done?'Done':'Open')+'</small></div><div class="task-actions"><button type="button" data-task="'+esc(t.id)+'" data-action="toggle">'+(t.done?'Reopen':'Mark done')+'</button><button type="button" data-task="'+esc(t.id)+'" data-action="edit">Edit</button><button type="button" data-task="'+esc(t.id)+'" data-action="delete">Delete</button></div></div>').join(''):'<p class="subtle">No tasks yet. Add one when the next step needs an owner.</p>'}
$('taskform').onsubmit=e=>{e.preventDefault();try{const text=$('tasktext').value.trim(),owner=$('taskowner').value.trim();if(!text)throw Error('Enter a task.');const n=clone(state);if(editingTask){const i=n.tasks.findIndex(t=>t.id===editingTask);if(i<0)throw Error('Task no longer exists.');n.tasks[i]={...n.tasks[i],text,owner}}else{if(n.tasks.length>=100)throw Error('This preview supports up to 100 tasks.');n.tasks.push({id:crypto.randomUUID(),text,owner,done:false})}commit(n);editingTask=null;$('taskform').reset();$('taskform').querySelector('button').textContent='Add task';renderTasks();notice('Task saved locally. No message was sent.')}catch(e){notice(e.message,true)}};
$('tasks').onclick=e=>{const b=e.target.closest('[data-task]');if(!b)return;try{const n=clone(state),i=n.tasks.findIndex(t=>t.id===b.dataset.task);if(i<0)return;if(b.dataset.action==='edit'){editingTask=n.tasks[i].id;$('tasktext').value=n.tasks[i].text;$('taskowner').value=n.tasks[i].owner;$('taskform').querySelector('button').textContent='Save task';$('tasktext').focus();return}if(b.dataset.action==='delete'){if(!confirm('Delete this internal task?'))return;n.tasks.splice(i,1)}else n.tasks[i].done=!n.tasks[i].done;commit(n);renderTasks()}catch(e){notice(e.message,true)}};
function renderQA(){$('qa').innerHTML=checks.map(([id,label])=>'<div class="qa-row"><div class="qa-title"><b>'+id+'</b><span>'+label+'</span></div><div class="qa-controls"><label>Result<select aria-label="'+id+' result" data-qa="'+id+'" data-field="status">'+['NOT TESTED','PASS','FAIL','BLOCKED'].map(v=>'<option '+((state.qa[id]?.status||'NOT TESTED')===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>Observed result / error<textarea aria-label="'+id+' notes" data-qa="'+id+'" data-field="note" maxlength="4000" rows="2">'+esc(state.qa[id]?.note||'')+'</textarea></label></div></div>').join('')}
$('qa').addEventListener('input',e=>{const x=e.target;if(!x.dataset.qa)return;try{const n=clone(state);n.qa[x.dataset.qa]??={status:'NOT TESTED',note:''};n.qa[x.dataset.qa][x.dataset.field]=x.value;commit(n)}catch(err){qaUnsaved=true;notice(err.message+' Download your typed test results before leaving.',true)}});
$('downloadqa').onclick=()=>{const lines=['BAYSTEAD PARTS | BROWSER TEST RESULTS','Recorded: '+new Date().toISOString(),'Fictional browser workspace; operator-recorded results, not automated proof.',''];for(const[id,label]of checks){lines.push(id+' — '+label,'RESULT: '+document.querySelector('[data-qa="'+id+'"][data-field="status"]').value,'NOTES: '+(document.querySelector('[data-qa="'+id+'"][data-field="note"]').value||'NOT PROVIDED'),'')}download('Baystead-Browser-Test-Results.txt',lines.join('\r\n'),'text/plain;charset=utf-8');notice('Test results prepared. Attach the saved file to your reply to Steen.')};
function reset(){if(!confirm('Reset this fictional browser workspace, saved job, tasks and test results? Download a workspace backup first. Unsaved drafts will be discarded.'))return;try{assertFresh();const next={job:null,tasks:[],qa:{}};baseline=writeStored(localStorage,KEY,baseline,next);storageBroken=false;state=next;previous=null;qaUnsaved=false;clearBackupLink();clearRestorePreview();refreshWorkspace();notice('Fictional workspace reset.')}catch(e){notice(e.message||'Browser storage could not be cleared.',true)}}
$('reset').onclick=$('reset-mobile').onclick=reset;
window.addEventListener('beforeunload',e=>{if(hasDraft()||qaUnsaved){e.preventDefault();e.returnValue=''}});
renderJob();renderTasks();renderQA();recoveryControls();




function clearBackupLink(){if(backupURL)URL.revokeObjectURL(backupURL);backupURL=null;$('backup-ready').hidden=true;$('backup-save').removeAttribute('href')} 
function recoveryMessage(text,error=false){$('recovery-status').textContent=text;$('recovery-status').classList.toggle('error',error)}
function recoveryControls(){$('undo-restore').hidden=previous===null;$('rollback-note').hidden=previous===null;}
function clearRestorePreview(){previewSerial++;pendingRestore=null;$('restore-preview').hidden=true;$('restore-confirm').checked=false;$('restore-apply').disabled=true;}
function refreshWorkspace(){dirty=false;editingTask=null;pendingFile=null;$('taskform').reset();$('taskform').querySelector('button').textContent='Add task';$('import').value='';$('verifyresult').textContent='';renderJob();renderTasks();renderQA();recoveryControls();}
function describeWorkspace(value){const x=workspaceSummary(value);return x.job+(x.revision===null?'':' · Revision '+x.revision+' · '+x.approval)+' · '+x.tasks+' tasks ('+x.openTasks+' open) · '+x.recordedTests+' of 8 tests with a result or note';}
$('backup-download').onclick=async()=>{try{requireClean();const atStart=baseline,packet=await makeBackup(state);requireClean();if(baseline!==atStart)throw Error('Workspace changed while preparing the backup. Try again.');clearBackupLink();backupURL=URL.createObjectURL(new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}));$('backup-save').href=backupURL;$('backup-save').download='Baystead-Workspace-'+packet.createdAt.slice(0,10)+'.json';$('backup-ready').hidden=false;$('backup-save').click();recoveryMessage('Backup prepared for download. Check your Downloads folder and keep the file somewhere safe. Only saved work is included.')}catch(e){recoveryMessage(e.message,true)}};
$('backup-file').onchange=()=>{clearRestorePreview();recoveryMessage('Choose Preview backup to inspect this file before making any changes.')};
$('restore-preview-button').onclick=async()=>{
  clearRestorePreview();const request=previewSerial;
  try{
    requireClean();const file=$('backup-file').files[0],atStart=baseline;
    if(!file)throw Error('Choose a Baystead workspace backup JSON file first.');
    if(file.size>MAX_BACKUP_BYTES)throw Error('Choose a backup smaller than 1 MB.');
    const packet=await readBackup(await file.text());
    if(request!==previewSerial)return;
    requireClean();if(baseline!==atStart)throw Error('Workspace changed during preview. Preview the file again.');
    pendingRestore={packet,baseline:atStart};
    $('restore-current').textContent=describeWorkspace(state);
    $('restore-incoming').textContent=describeWorkspace(packet.workspace);
    $('restore-created').textContent=new Date(packet.createdAt).toLocaleString();
    $('restore-preview').hidden=false;
    recoveryMessage('Backup checks passed. Review both workspaces below. Nothing has been changed.');
    $('restore-preview').scrollIntoView({behavior:'smooth',block:'nearest'});
  }catch(e){if(request===previewSerial)recoveryMessage(e.message,true)}
};
$('restore-confirm').onchange=()=>{$('restore-apply').disabled=!$('restore-confirm').checked||!pendingRestore};
$('restore-cancel').onclick=()=>{clearRestorePreview();recoveryMessage('Restore cancelled. Your current workspace is unchanged.');$('restore-preview-button').focus()};
$('restore-apply').onclick=()=>{
  try{requireClean();if(!pendingRestore||!$('restore-confirm').checked)throw Error('Preview the backup and confirm replacement first.');if(baseline!==pendingRestore.baseline)throw Error('The workspace changed after preview. Preview the backup again.');const next=clone(pendingRestore.packet.workspace),old=clone(state);commit(next,old);qaUnsaved=false;refreshWorkspace();recoveryMessage('Workspace restored. The previous workspace is available through Undo restore until your next saved change.');notice('Backup restored. Review the restored job and test results.');$('undo-restore').focus()}catch(e){recoveryMessage(e.message,true)}
};
$('undo-restore').onclick=()=>{try{requireClean();if(previous===null)throw Error('There is no restore to undo.');commit(clone(previous));refreshWorkspace();recoveryMessage('Restore undone. Your previous workspace is back.');notice('Your previous workspace has been restored.')}catch(e){recoveryMessage(e.message,true)}};
