export const sample={estimateId:'SYN-WORKBENCH-001',locationId:'SYN-LOCATION-01',vehicle:'2021 Honda Accord',parts:[{lineId:'010',description:'Front bumper cover',partNumber:'04711-TVA-A00',partType:'OEM',quantity:1,unitPriceCents:63500,supplier:'Synthetic OEM Supply'},{lineId:'020',description:'Left headlamp assembly',partNumber:'33150-TVA-A01',partType:'OEM',quantity:1,unitPriceCents:82500,supplier:'Synthetic OEM Supply'},{lineId:'030',description:'Hood panel',partNumber:'60100-TVA-A00',partType:'OEM',quantity:1,unitPriceCents:72000,supplier:'Synthetic OEM Supply'},{lineId:'040',description:'Upper grille',partNumber:'71121-TVA-A10',partType:'AFTERMARKET',quantity:1,unitPriceCents:19800,supplier:'Synthetic Parts Co.'},{lineId:'050',description:'Bumper side bracket',partNumber:'71193-TVA-A00',partType:'OEM',quantity:1,unitPriceCents:4200,supplier:'Synthetic OEM Supply'},{lineId:'060',description:'Left front door blend',partNumber:'PAINT-BLEND-01',partType:'UNKNOWN',quantity:1,unitPriceCents:0,supplier:'Synthetic Labor'}]};
const clone=v=>JSON.parse(JSON.stringify(v)),now=()=>new Date().toISOString();
export function parseMoney(input){const s=String(input??'').trim();if(!/^\d+(?:\.\d{1,2})?$/.test(s))throw Error('Money must be a non-negative decimal with up to two places.');const [w,f='']=s.split('.'),n=Number(w)*100+Number(f.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n>100000000)throw Error('Money is outside the supported range.');return n;}
const text=(v,l,m=240)=>{if(typeof v!=='string'||!v.trim()||v.length>m)throw Error(`${l} is invalid.`);return v};
export function validateParts(parts){if(!Array.isArray(parts)||parts.length<1||parts.length>200)throw Error('Parts must contain 1–200 lines.');const ids=new Set();return parts.map(p=>{const id=text(p?.lineId,'Line ID',40);if(ids.has(id))throw Error('Line IDs must be unique.');ids.add(id);if(!Number.isSafeInteger(p.quantity)||p.quantity<1||p.quantity>100)throw Error('Quantity must be a whole number from 1 to 100.');if(!Number.isSafeInteger(p.unitPriceCents)||p.unitPriceCents<0||p.unitPriceCents>100000000)throw Error('Unit price cents is invalid.');return {...p,lineId:id,description:text(p.description,'Description'),partNumber:text(p.partNumber,'Part number',120),partType:text(p.partType,'Part type',40),supplier:text(p.supplier,'Supplier',120)};});}
export function total(parts){return validateParts(parts).reduce((n,p)=>n+p.quantity*p.unitPriceCents,0);}
export function validateJob(j){if(!j||typeof j!=='object')throw Error('Job is invalid.');text(j.estimateId,'Estimate ID',80);text(j.locationId,'Location ID',80);text(j.vehicle,'Vehicle',120);if(!Number.isSafeInteger(j.version)||j.version<0)throw Error('Job version is invalid.');const parts=validateParts(j.parts);if(!j.original||typeof j.original!=='object'||j.original.estimateId!==j.estimateId||j.original.locationId!==j.locationId||j.original.vehicle!==j.vehicle)throw Error('Original snapshot is invalid.');const original=validateParts(j.original.parts);if(original.length!==parts.length||original.some((p,i)=>['lineId','description','partNumber','partType','supplier'].some(k=>p[k]!==parts[i][k])))throw Error('Part identity or metadata was changed.');if(!Array.isArray(j.history)||j.history.length!==j.version)throw Error('Revision history does not match the job version.');let reconstructed=original.map(p=>({...p}));j.history.forEach((h,i)=>{if(!h||h.version!==i+1||typeof h.reason!=='string'||!h.reason.trim()||h.reason.length>500||Number.isNaN(Date.parse(h.savedAt))||!Array.isArray(h.changes)||!h.changes.length)throw Error('Revision history entry is invalid.');for(const c of h.changes){const line=reconstructed.find(p=>p.lineId===c.lineId);if(!line||!['quantity','unitPriceCents'].includes(c.field)||c.before!==line[c.field])throw Error('Revision history before value is invalid.');line[c.field]=c.after;}reconstructed=validateParts(reconstructed);});if(JSON.stringify(reconstructed)!==JSON.stringify(parts))throw Error('Revision history does not reconstruct the saved job.');if(j.approved!==null&&j.approved!==false&&(!j.approved||j.approved.version!==j.version||j.version<1||Number.isNaN(Date.parse(j.approved.at))))throw Error('Approval is invalid.');return true;}
export function createJob(source=sample){const b={...clone(source),version:0,history:[],approved:null,reason:''};validateParts(b.parts);return {...b,original:clone(source)};}
export function saveRevision(job,draft,reason){validateJob(job);const r=text(reason,'Revision reason',500);const next=validateParts(draft),old=job.parts;if(next.length!==old.length||next.some((p,i)=>Object.keys(p).some(k=>!['quantity','unitPriceCents'].includes(k)&&p[k]!==old[i][k])))throw Error('Only quantity and unit price may be edited in this preview.');if(JSON.stringify(next)===JSON.stringify(old))throw Error('No changes to save.');const changes=next.flatMap((p,i)=>['quantity','unitPriceCents'].filter(k=>p[k]!==old[i][k]).map(field=>({lineId:p.lineId,field,before:old[i][field],after:p[field]})));return {...clone(job),parts:clone(next),version:job.version+1,reason:r,approved:null,history:[...job.history,{version:job.version+1,reason:r,savedAt:now(),changes}]};}
export function approveJob(job){validateJob(job);if(job.version<1)throw Error('Save a revision before approval.');return {...clone(job),approved:{version:job.version,at:now()}};}
export async function hashJson(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(v)));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function makeExport(job){validateJob(job);if(!job.approved||job.approved.version!==job.version)throw Error('Approve the current revision before export.');const x=clone(job);return {format:'baystead-parts-browser-review/v1',job:x,jobDigest:await hashJson(x),authority:{ordering:false,partsTrader:false,liveWrite:false}};}
export async function verifyExport(p,currentJob=null){if(p?.format!=='baystead-parts-browser-review/v1'||!p.job||typeof p.jobDigest!=='string'||JSON.stringify(p.authority)!==JSON.stringify({ordering:false,partsTrader:false,liveWrite:false}))throw Error('This is not a valid local Baystead review file.');validateJob(p.job);if(!p.job.approved||p.job.approved.version!==p.job.version)throw Error('Blocked: the review file is not currently approved.');const sha256=await hashJson(p.job);if(sha256!==p.jobDigest)throw Error('Blocked: review file digest does not match its saved content.');return {valid:true,sha256,status:currentJob&&await hashJson(currentJob)===sha256?'Current saved revision':'Historical/different workspace'};}

